[project]
org-name= "laf"
version= "0.1.1"
authors = ["lafernando"]
repository = "https://github.com/lafernando/module-zip"
keywords = ["zip", "utilities"]
license = ["Apache-2.0"]

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    path = "./lib/java/build/libs/libzip.jar"
    modules = ["zip"]
